### ISSUE TITLE
Allow App to be Hosted at Subdirectory

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-deidentifier-app#22]
### Problem description

The app fails if it is not hosted at root (i.e. `/`).

#### Steps to reproduce the issue

1. Checkout `add-tools-stack` branch of [aws-cloudformation repo](https://github.com/nlpsandbox/aws-cloudformation/tree/add-tools-stack)
2. Run `docker-compose up --build`
3. Navigate to `http://localhost/phi-deidentifier`
4. You should see a blank page.

#### Expected behavior

You should see the app, not a blank page.

#### Extra information

React documentation has [a guide](https://create-react-app.dev/docs/deployment/#building-for-relative-paths) for serving React apps from subdirectories

**Comment by tschaffter** [comment]
This would offer a greater flexibility but this is no longer needed.
