### ISSUE TITLE
Release PHI Deidentifier app for schema 1.0.1

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/phi-deidentifier-app#23]

**Comment by cascadianblue** [comment]
@tschaffter I want to make sure I understand this ticket; I am supposed to incorporate schema v1.0.1 into the web client after the version is released, right?

**Comment by tschaffter** [comment]
Yes for the PHI Deidentifier API service and React app. I'll update the data node and the four example annotators. @thomasyu888 will update the Python client. I'll update this ticket when I release the new schema tomorrow morning. Meanwhile, if there is a last minute change you want to make to the schema, you can still do it today.

**Comment by tschaffter** [comment]
Done
