### ISSUE TITLE
Change the default text in the right box to gray or disable

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/phi-deidentifier-app#35]
The black color give a false sense that the user can edit the default text in the right box.
Also, consider displaying the default text in the right box if the left box is empty and the user clicks on "De-identify".

![image](https://user-images.githubusercontent.com/3056480/109371063-f2725880-7857-11eb-90af-5678194537af.png)

**Comment by cascadianblue** [comment]
@tschaffter should the de-identified text always be gray or something else?
